// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksAPI.Models;

namespace ParksAPI.Migrations
{
    [DbContext(typeof(ParksAPIContext))]
    [Migration("20210614062621_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksAPI.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ParkName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Size")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Description = "Music, river, events",
                            ParkName = "Drake Park",
                            Size = "Medium"
                        },
                        new
                        {
                            ParkId = 2,
                            Description = "Gazebos, playground",
                            ParkName = "Esther Short",
                            Size = "Medium"
                        },
                        new
                        {
                            ParkId = 3,
                            Description = "Music, Dancing, Trees",
                            ParkName = "Mount Tabor",
                            Size = "Large"
                        },
                        new
                        {
                            ParkId = 4,
                            Description = "Beach, pavillions, grills",
                            ParkName = "Cottonwood",
                            Size = "Small"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
